# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.srcs/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0.xci
# IP: The module: 'CamRead_FIFO_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.gen/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CamRead_FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.gen/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'CamRead_FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.gen/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CamRead_FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.srcs/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0.xci
# IP: The module: 'CamRead_FIFO_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.gen/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CamRead_FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.gen/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'CamRead_FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/George/Desktop/Edge-Detection/HDMI_test2/HDMI_test2.gen/sources_1/bd/CamRead_FIFO/ip/CamRead_FIFO_fifo_generator_0_0/CamRead_FIFO_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CamRead_FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
