# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/greyscale_algorithm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm || ORIG_REF_NAME==greyscale_algorithm} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_0_0/greyscale_algorithm_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm_floating_point_0_0 || ORIG_REF_NAME==greyscale_algorithm_floating_point_0_0} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_1_0/greyscale_algorithm_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm_floating_point_1_0 || ORIG_REF_NAME==greyscale_algorithm_floating_point_1_0} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_2_0/greyscale_algorithm_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm_floating_point_2_0 || ORIG_REF_NAME==greyscale_algorithm_floating_point_2_0} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_3_0/greyscale_algorithm_floating_point_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm_floating_point_3_0 || ORIG_REF_NAME==greyscale_algorithm_floating_point_3_0} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_4_0/greyscale_algorithm_floating_point_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm_floating_point_4_0 || ORIG_REF_NAME==greyscale_algorithm_floating_point_4_0} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_5_0/greyscale_algorithm_floating_point_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm_floating_point_5_0 || ORIG_REF_NAME==greyscale_algorithm_floating_point_5_0} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_6_0/greyscale_algorithm_floating_point_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyscale_algorithm_floating_point_6_0 || ORIG_REF_NAME==greyscale_algorithm_floating_point_6_0} -quiet] -quiet

# Block Designs: C:/Users/George/Edge-Detection/camera_interface/camera_interface.srcs/sources_1/bd/BRAM_1_FIFO/BRAM_1_FIFO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_1_FIFO || ORIG_REF_NAME==BRAM_1_FIFO} -quiet] -quiet

# IP: C:/Users/George/Edge-Detection/camera_interface/camera_interface.srcs/sources_1/bd/BRAM_1_FIFO/ip/BRAM_1_FIFO_fifo_generator_0_0/BRAM_1_FIFO_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_1_FIFO_fifo_generator_0_0 || ORIG_REF_NAME==BRAM_1_FIFO_fifo_generator_0_0} -quiet] -quiet

# XDC: c:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_0_0/greyscale_algorithm_floating_point_0_0_ooc.xdc

# XDC: c:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_1_0/greyscale_algorithm_floating_point_1_0_ooc.xdc

# XDC: c:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_2_0/greyscale_algorithm_floating_point_2_0_ooc.xdc

# XDC: c:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_3_0/greyscale_algorithm_floating_point_3_0_ooc.xdc

# XDC: c:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_4_0/greyscale_algorithm_floating_point_4_0_ooc.xdc

# XDC: c:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_5_0/greyscale_algorithm_floating_point_5_0_ooc.xdc

# XDC: c:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/ip/greyscale_algorithm_floating_point_6_0/greyscale_algorithm_floating_point_6_0_ooc.xdc

# XDC: C:/Users/George/Edge-Detection/greyscale-v5/greyscale-v5.srcs/sources_1/bd/greyscale_algorithm/greyscale_algorithm_ooc.xdc

# XDC: c:/Users/George/Edge-Detection/camera_interface/camera_interface.srcs/sources_1/bd/BRAM_1_FIFO/ip/BRAM_1_FIFO_fifo_generator_0_0/BRAM_1_FIFO_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BRAM_1_FIFO_fifo_generator_0_0 || ORIG_REF_NAME==BRAM_1_FIFO_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/George/Edge-Detection/camera_interface/camera_interface.srcs/sources_1/bd/BRAM_1_FIFO/ip/BRAM_1_FIFO_fifo_generator_0_0/BRAM_1_FIFO_fifo_generator_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==BRAM_1_FIFO_fifo_generator_0_0 || ORIG_REF_NAME==BRAM_1_FIFO_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/George/Edge-Detection/camera_interface/camera_interface.srcs/sources_1/bd/BRAM_1_FIFO/ip/BRAM_1_FIFO_fifo_generator_0_0/BRAM_1_FIFO_fifo_generator_0_0_ooc.xdc

# XDC: C:/Users/George/Edge-Detection/camera_interface/camera_interface.srcs/sources_1/bd/BRAM_1_FIFO/BRAM_1_FIFO_ooc.xdc
