@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jan 28 18:03:30 -0800 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim test2_thrugreyscale_tb_behav -key {Behavioral:sim_1:Functional:test2_thrugreyscale_tb} -tclbatch test2_thrugreyscale_tb.tcl -protoinst "protoinst_files/BRAM_1_FIFO.protoinst" -view C:/Users/George/Edge-Detection/test-phase2/camera_config_tb.wcfg -log simulate.log"
call xsim  test2_thrugreyscale_tb_behav -key {Behavioral:sim_1:Functional:test2_thrugreyscale_tb} -tclbatch test2_thrugreyscale_tb.tcl -protoinst "protoinst_files/BRAM_1_FIFO.protoinst" -view C:/Users/George/Edge-Detection/test-phase2/camera_config_tb.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
